steps:
  - id: "Build Test Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "."
      - "-t"
      - "teds-test"
      - '-f'
      - 'RunTestsDockerfile'

  - id: "Test Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "run"
      - "teds-test"

  - id: "Build GCR Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "."
      - "-t"
      - "gcr.io/nectar-bazaar/teds"

  - id: "Push to GCR"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "push"
      - "gcr.io/nectar-bazaar/teds"
