steps:
  - id: "Build Test Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "."
      - "-t"
      - "testing"

  - id: "Test Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "run"
      - "testing"
