images:
  - "gcr.io/nectar-bazaar/teds"

steps:
  - id: "Pull Latest"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "pull"
      - "gcr.io/nectar-bazaar/python-rubies:latest"

  - id: "Build Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Pull Latest"]
    args:
      - "build"
      - "."
      - "-t"
      - "teds"
      - "-t"
      - "gcr.io/nectar-bazaar/teds"
      - "--cache-from"
      - "gcr.io/nectar-bazaar/python-rubies:latest"

  - id: "Run Tests"
    waitFor: ["Build Image"]
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "run"
      - "--env"
      - "CODECOV_TOKEN=${_CODECOV_TOKEN}"
      - "teds"
      - "test"