images:
  - "gcr.io/nectar-bazaar/teds"

steps:
  - id: "Pull Latest"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "pull"
      - "gcr.io/nectar-bazaar/teds"

  - id: "Build Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["Pull Latest"]
    args:
      - "build"
      - "."
      - "-t"
      - "teds"
      - "-t"
      - "gcr.io/nectar-bazaar/teds"
      - "--from-cache"
      - "gcr.io/nectar-bazaar/teds"

  - id: "Run Tests"
    waitFor: ["Build Image"]
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "run"
      - "teds"
      - "test"