steps:
#  - id: "Build Test Image"
#    name: 'gcr.io/cloud-builders/docker'
#    args:
#      - "build"
#      - "."
#      - "-t"
#      - "testing"
#      - '-f'
#      - 'RunTestsDockerfile'
#
#  - id: "Test Image"
#    name: 'gcr.io/cloud-builders/docker'
#    args:
#      - "run"
#      - "testing"

  - id: "Build GCR Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "."
      - "-t"
      - "gcr.io/nectar-bazaar/helm-ted"

  - id: "Test Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "push"
      - "gcr.io/nectar-bazaar/helm-ted"
